KAFKA_SERVER = "kafka:9092"
KAFKA_TOPIC_CREATE = "task-created"
KAFKA_TOPIC_DELETE = "task-deleted"
KAFKA_GROUP_ID = "notification-group"
DB_URL = "postgresql+asyncpg://admin:12345678@postgres:5432/ProTaskBD"
REDIS_URL = "redis://redis:6379"